Phonebook.Frontend/src/app/modules/table/table-logic.ts
=> fix(table): fix filter and search with blanks

Phonebook.Frontend/.releaserc.json
- fix some other pluging steps not loaded before
=> chore(release): update release with github plugin

Phonebook.Frontend/karma.conf.js, Phonebook.Frontend/package.json, Phonebook.Frontend/protractor.conf.js
=> Fix Frontend Builds

Phonebook.Frontend/.releaserc.json, Phonebook.Frontend/package-lock.json, Phonebook.Frontend/package.json, Phonebook.Frontend/proxy.conf.json, Phonebook.Frontend/src/app/app.component.spec.ts, Phonebook.Frontend/src/app/services/release-info.service.spec.ts, Phonebook.Frontend/src/app/services/release-info.service.ts, Phonebook.Frontend/src/app/shared/dialogs/release-notification-dialog/release-notification.dialog.html, Phonebook.Frontend/src/app/shared/dialogs/release-notification-dialog/release-notification.dialog.ts
New Versions, Features and Bugfixes are automatically shown in the Release-Notification. 
Related: #55
=> feat(app): show generated release notes

.azure/pipelines/pr/Phonebook.Frontend.pr.yml
Fail if package.json and package-lock.json are out of sync
=> Update Phonebook.Frontend.pr.yml for Azure Pipelines

phonebook.code-workspace
- add recommendated extension
- add Folders
=> chore(util): make workspace useful

Phonebook.Frontend/.releaserc.json, Phonebook.Frontend/getChangelog.js
- changelog is now persisteted with the release
- changes from earlier versions are visible in newer versions
=> feat(app): add static changelog

Phonebook.Frontend/src/app/shared/config/ColumnDefinitions.spec.ts, Phonebook.Frontend/src/app/shared/config/columnDefinitions.ts
Honor spaces in user searches for the fullname
Resolves #62
=> fix(table): full name search shows result

Phonebook.Frontend/nginx/nginx.conf
- make use of angular service worker self desctruction by delivering 404
Resolves #61
=> fix(service-worker): uninstall service-worker

Phonebook.Frontend/src/app/modules/table/components/table/table.component.html, Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.html, Phonebook.Frontend/src/app/shared/config/columnTranslate.ts, Phonebook.Frontend/src/i18n/messages.de.xlf, Phonebook.Frontend/src/i18n/messages.en.xlf, Phonebook.Frontend/src/i18n/messages.test.xlf, Phonebook.Frontend/src/i18n/messages.xlf, docs/developer-guide/translation-guide.md
=> fix(app): rename costcenter to profitcenter

Phonebook.Frontend/src/migration/Migration.ts, Phonebook.Frontend/src/migration/migrations/3/migration3.spec.ts, Phonebook.Frontend/src/migration/migrations/3/migration3.ts, Phonebook.Frontend/src/migration/migrations/index.ts
=> fix(settings): load theme if page was loaded before

Phonebook.Frontend/src/app/shared/components/room-plan/room-plan.component.html, Phonebook.Frontend/src/app/shared/components/room-plan/room-plan.component.ts
- does not use a white list of filenames anymore
=> fix(app): automatically get svg or jpg

docs/README.md
=> update links in readme

Phonebook.Frontend/src/app/shared/components/room-plan/room-plan.component.ts
Polygons were not colored in the floorplan. Because of that many rooms were not colored.
TFS: Bug 7493
=> fix(floorplan): color polygons as well

Phonebook.Frontend/src/app/app.module.ts, Phonebook.Frontend/src/app/shared/config/columnDefinitions.ts
=> fix(search): make search respect accents

Phonebook.Frontend/src/app/shared/components/room-plan/room-plan.component.ts
resolves #110 
If user is changing the svg will try to reload.
I'am not sure if this is the best solution but it will fix the critical bug for now.
=> fix(floorplan): add loadSVG to ngOnChanges

docs/pages/development-guides/frontend/getting-started.md
Remove a command that is not necessary. The command is already in the "run start" pipe
=> docs(docs): remove not necessary command

Phonebook.Frontend/README.md
=> docs(docs): update link

docs/README.md
Community information
> Please take a look for spelling mistakes.
=> docs(docs): insert community information into readme.md

Phonebook.Frontend/src/index.html
=> fix(app): make app work in safari

Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.html
**Only line 3 has changed.** The others are cause of prettier.
If the user want to open the sidenav on small devices it will now open the sidenav on the right side. It opened on the left side before and was a little bit strange because the burger is on the right side.
=> feature(app): open sidenav on small devices on the right side

Phonebook.Frontend/package.json, phonebook.code-workspace
Co-Authored-By: danielhabenicht <daniel-habenicht@outlook.de>
=> chore: update workspace settings and scripts

docs/README.md
Lists all contributors as Co-Author
Co-Authored-By: schurzi <schurzi@users.noreply.github.com>
Co-Authored-By: danielsy <danielsy@users.noreply.github.com>
Co-Authored-By: renkin <renkin@users.noreply.github.com>
Co-Authored-By: oliverguhr <oliverguhr@users.noreply.github.com>
=> docs: update contributors

Phonebook.Frontend/src/app/shared/states/Search.state.ts
=> fix(frontend-search): search does not reset on user page

Phonebook.Frontend/src/app/modules/profile-picture/components/change-profile-picture-dialog/change-profile-picture-dialog.component.html, Phonebook.Frontend/src/i18n/messages.de.xlf, Phonebook.Frontend/src/i18n/messages.en.xlf, Phonebook.Frontend/src/i18n/messages.test.xlf, Phonebook.Frontend/src/i18n/messages.xlf
=> fix(frontend-upload): add delete information

Phonebook.Frontend/.dockerignore, Phonebook.Frontend/Dockerfile, Phonebook.Frontend/nginx/nginx.conf, Phonebook.Frontend/opensearch.xml, Phonebook.Frontend/src/index.html, Phonebook/phonebook/templates/frontend-deployment.yaml
=> fix(frontend): opensearch.xml available under root

docs/pages/development-guides/general-guide.md
=> docs: update frontend-link in general-guide.md

.azure/pipelines/Phonebook.preview.yml
This fixes the task beeing canceled after 30 minutes.
=> Update Phonebook.preview.yml for Azure Pipelines

Phonebook.Frontend/.gitignore, Phonebook.Frontend/.vscode/i18n.code-snippets, Phonebook.Frontend/.vscode/snippets/i18n.code-snippets
This pr is adding i18n-snippets for html and typescript.
https://www.thomasbembridge.com/adding-vscode-snippets-to-your-project/
https://code.visualstudio.com/updates/v1_28#_project-level-snippets
=> feat(chore): add i18n code-snippets

Phonebook.Frontend/src/app/services/release-info.service.ts
=> fix(release-notification): Hide release-notification-badge if release-dialog was clicked

Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.html
I think that this will looks a bit nicer.
=> fix(user-greeting): add exclamation mark

docs/_config.yml, docs/_layouts/default.html, docs/pages/development-guides/frontend/theme-development.md
Resolves #177 
I don't really know why the bug happened but this will fix the layout. Probably because of an `just-the-docs` update.
Also inserted the new contact-email.
=> docs: fix layout and insert email-adress

Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.html
=> fix(release-dialog): move click-event to right element (button)

Phonebook.Frontend/src/app/modules/profile-picture/components/profile-picture/profile-picture.component.html, Phonebook.Frontend/src/app/modules/profile-picture/components/profile-picture/profile-picture.component.scss
=> fix(pictures): fix placeholders off center in edge

.github/workflows/main.yml
Add Automerger for PRs
Find Dokumentation here: https://github.com/marketplace/actions/merge-pull-requests
=> Add main.yml

.azure/pipelines/Phonebook.preview.yml, .azure/pipelines/production/Phonebook.Frontend.yml
- remediate error
- use bot account
closes #52
=> Use new Credentials

.azure/pipelines/production/Phonebook.Assets.yml, .azure/pipelines/production/Phonebook.Source.MockPeopleBackend.yml
Remediate error when running with the new credentials.
=> Update Phonebook.Assets.yml for Azure Pipelines

Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.html, Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.scss
This pr will just rename pb-card-container to pb-justify-center.
The class is defined in #202.
*This pr and #202 need to be released together.*
**Blocked until #202 is merged**
=> fix(notification-dialog): rename pb-card-container

Phonebook.Frontend/src/app/modules/table/components/table/table.component.html, Phonebook.Frontend/src/app/modules/table/table-logic.spec.ts, Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.html, Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.ts, Phonebook.Frontend/src/app/shared/config/ColumnDefinitions.spec.ts, Phonebook.Frontend/src/app/shared/config/columnDefinitions.ts, Phonebook.Frontend/src/app/shared/config/columnTranslate.ts, Phonebook.Frontend/src/app/shared/mocks/person.ts, Phonebook.Frontend/src/app/shared/models/classes/Person.ts, Phonebook.Frontend/src/app/shared/models/classes/index.ts, Phonebook.Frontend/src/app/shared/models/enumerables/ColumnId.ts, Phonebook.Frontend/src/app/shared/models/enumerables/PersonStatus.ts, Phonebook.Frontend/src/app/shared/models/enumerables/index.ts, Phonebook.Frontend/src/i18n/messages.de.xlf, Phonebook.Frontend/src/i18n/messages.en.xlf, Phonebook.Frontend/src/i18n/messages.test.xlf, Phonebook.Frontend/src/i18n/messages.xlf
=> feat(filter): make filter for employee-type possible

Phonebook.Demo/values.yml, Phonebook.Frontend/src/app/app.component.ts, Phonebook.Frontend/substitute_variables.sh
resolves #214 
resolves #260 
resolves part of #99
=> fix(bug-report-dialog): Don't show Bug Report Dialog if no ravenUrl is provided

Phonebook.Frontend/package.json
=> chore: update package.json

Phonebook.Frontend/src/app/shared/config/columnTranslate.ts
=> fix(columnTranslate): workaround for filters in english version

Phonebook.Frontend/.prettierrc.json, phonebook.code-workspace
create a settings-file for prettier
This will not solve issue #350 !
=> chore: create .prettierrc.json

.all-contributorsrc
=> chore: fix .all-contributorsrc

.github/workflows/main.yml
Reverts T-Systems-MMS/phonebook#218
Seems to work again so we can readd it.
=> chore: add automerge

Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.ts
=> bug(table-configurator): prevent multiple dialogs (#387)

Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.html, Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.scss, Phonebook.Frontend/src/app/shared/components/navigation/navigation.component.ts, Phonebook.Frontend/src/styles.scss, Phonebook.Frontend/src/styles/mixins.scss
i added the profile picture in the navbar and put the buttons of the navbar into a flexbox to center
them vertically
=> feat(navbar): profile Picture in Navbar instead of person-icon

Phonebook.Frontend/src/app/app.component.ts
refactor commit message for auto release
=> fix(skip-start-dialogs): skip release information and bug report dialog

Phonebook.Frontend/src/app/services/mail.service.ts
#423 
Here is the new PR for fixing the mailservice
=> fix(mailservice) : subject fixed

.gitattributes
=> chore(lineendings): partly reverting the last fix

Phonebook/phonebook/requirements.yaml
Reverts T-Systems-MMS/phonebook#402
Because of https://github.com/helm/charts/issues/19111
=> Revert "chore(deps): update helm chart traefik to v1.82.3"

Phonebook.Frontend/src/app/modules/rooms/components/building/building.component.html, Phonebook.Frontend/src/app/modules/rooms/components/city/city.component.html, Phonebook.Frontend/src/app/modules/rooms/components/floor/floor.component.html, Phonebook.Frontend/src/app/modules/rooms/components/room/room.component.html, Phonebook.Frontend/src/app/shared/components/user/user-detail/user-detail.component.html, Phonebook.Frontend/src/styles/overrides.scss
fixes #459 
I thought the class overrides should be in but they were the reason for the error. Please have a look, test it in different browsers. For me everything works in edge, firefox, chrome.
=> fix(user-detail): too much whitespace 

Phonebook.Frontend/src/app/shared/components/room-plan/room-plan.component.html, Phonebook.Frontend/src/app/shared/components/room-plan/room-plan.component.scss
=> fix(room-plan): images are too big

Phonebook.Frontend/src/app/app.module.ts, Phonebook.Frontend/src/app/services/theme.service.ts, Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.html, Phonebook.Frontend/src/app/shared/dialogs/display-notification-dialog/display-notification.dialog.scss
=> fix(style): use font in dialog

Phonebook.Frontend/package-lock.json, Phonebook.Frontend/package.json, Phonebook.Frontend/proxy.conf.json, Phonebook.Frontend/src/app/services/release-info.service.ts
fixes #569 by using markdown-it instead of marked
=> chore(release-info): fix #569

Phonebook.Frontend/src/styles/overrides.scss
=> fix(dialog): fix whitespace in dialogs

Phonebook.Frontend/package.json
=> chore(tests): fix chrome version once and for all

Phonebook.Frontend/package-lock.json, Phonebook.Frontend/package.json, Phonebook.Frontend/src/app/modules/organigram/components/organigram-node/organigram-node.component.html, Phonebook.Frontend/src/app/modules/organigram/components/organigram-node/organigram-node.component.ts, Phonebook.Frontend/src/app/modules/organigram/organigram.module.ts, Phonebook.Frontend/src/app/modules/rooms/rooms.module.ts, Phonebook.Frontend/src/app/shared/components/user/user.module.ts, Phonebook.Frontend/src/app/shared/directives/action-drawer/action-drawer-sheet/action-drawer-sheet.component.html, Phonebook.Frontend/src/app/shared/directives/action-drawer/action-drawer-sheet/action-drawer-sheet.component.ts, Phonebook.Frontend/src/app/shared/directives/action-drawer/action-drawer.directive.ts, Phonebook.Frontend/src/app/shared/directives/action-drawer/action-drawer.module.ts
=> fix(copy): use new cdk function instead of extra package

.azure/pipelines/Phonebook.preview.yml, demo/values.yml, docs/README.md
New domain is: https://demo-phonebook.aquiver.de
fixes #701
=> chore(demo): use new domain

Phonebook.Source.PeopleSoft/src/Phonebook.Source.PeopleSoft/Controllers/OrgUnitController.cs, Phonebook.Source.PeopleSoft/src/Phonebook.Source.PeopleSoft/Controllers/PeopleController.cs, Phonebook.Source.PeopleSoft/src/Phonebook.Source.PeopleSoft/Repositories/IRepository.cs, Phonebook.Source.PeopleSoft/src/Phonebook.Source.PeopleSoft/Repositories/OrgUnitRepository.cs, Phonebook.Source.PeopleSoft/src/Phonebook.Source.PeopleSoft/Startup.cs
3000ms vs. 300ms
the memory usage is now around 700mb
=> add caching for faster responses

docs/_layouts/default.html
Resolves #732 
Reason for the bug: I don't really know, but many stuff changed by the author of "just-the-docs".
=> docs: fix nav style issues
